from .chef_login_wid import Ui_Form as ChefLoginWid
from .chef_wid import Ui_Form as ChefWid
from .connect_wid import Ui_Form as ConnectWid
from .customer_login_wid import Ui_Form as CustomerLoginWid
from .customer_wid import Ui_Form as CustomerWid
from .manager_login_wid import Ui_Form as ManagerLoginWid
from .manager_wid import Ui_Form as ManagerWid
from .select_wid import Ui_Form as SelectWid
from .wait_wid import Ui_Form as WaitWid
