# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager_wid.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_refresh_on_order = QtWidgets.QPushButton(self.tab_2)
        self.bt_refresh_on_order.setObjectName("bt_refresh_on_order")
        self.horizontalLayout.addWidget(self.bt_refresh_on_order)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lb_name = QtWidgets.QLabel(self.tab_2)
        self.lb_name.setObjectName("lb_name")
        self.horizontalLayout_24.addWidget(self.lb_name)
        self.lb_table_no = QtWidgets.QLabel(self.tab_2)
        self.lb_table_no.setObjectName("lb_table_no")
        self.horizontalLayout_24.addWidget(self.lb_table_no)
        self.lb_status = QtWidgets.QLabel(self.tab_2)
        self.lb_status.setObjectName("lb_status")
        self.horizontalLayout_24.addWidget(self.lb_status)
        self.lb_total = QtWidgets.QLabel(self.tab_2)
        self.lb_total.setObjectName("lb_total")
        self.horizontalLayout_24.addWidget(self.lb_total)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_24.addWidget(self.label_17)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem2)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_24.addWidget(self.label_18)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.horizontalLayout_24.setStretch(0, 2)
        self.horizontalLayout_24.setStretch(1, 1)
        self.horizontalLayout_24.setStretch(2, 1)
        self.horizontalLayout_24.setStretch(3, 1)
        self.horizontalLayout_24.setStretch(4, 1)
        self.horizontalLayout_24.setStretch(5, 1)
        self.horizontalLayout_24.setStretch(6, 1)
        self.horizontalLayout_24.setStretch(7, 1)
        self.horizontalLayout_24.setStretch(8, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll12 = QtWidgets.QWidget()
        self.scroll12.setGeometry(QtCore.QRect(0, 0, 608, 254))
        self.scroll12.setObjectName("scroll12")
        self.scroll_on_order = QtWidgets.QVBoxLayout(self.scroll12)
        self.scroll_on_order.setObjectName("scroll_on_order")
        self.scrollArea.setWidget(self.scroll12)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 30)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.time_start = QtWidgets.QDateTimeEdit(self.tab_3)
        self.time_start.setObjectName("time_start")
        self.horizontalLayout_2.addWidget(self.time_start)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.time_end = QtWidgets.QDateTimeEdit(self.tab_3)
        self.time_end.setObjectName("time_end")
        self.horizontalLayout_2.addWidget(self.time_end)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 5)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 2)
        self.horizontalLayout_2.setStretch(6, 1)
        self.horizontalLayout_2.setStretch(7, 3)
        self.horizontalLayout_2.setStretch(8, 1)
        self.horizontalLayout_2.setStretch(9, 5)
        self.horizontalLayout_2.setStretch(10, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.bt_t_sale = QtWidgets.QPushButton(self.tab_3)
        self.bt_t_sale.setObjectName("bt_t_sale")
        self.horizontalLayout_3.addWidget(self.bt_t_sale)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.bt_get_orders = QtWidgets.QPushButton(self.tab_3)
        self.bt_get_orders.setObjectName("bt_get_orders")
        self.horizontalLayout_3.addWidget(self.bt_get_orders)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_25.addWidget(self.label_20)
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_25.addWidget(self.label_22)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_25.addWidget(self.label_21)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_25.addWidget(self.label_19)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem13)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 1)
        self.horizontalLayout_25.setStretch(2, 2)
        self.horizontalLayout_25.setStretch(3, 1)
        self.horizontalLayout_25.setStretch(4, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scroll_1 = QtWidgets.QWidget()
        self.scroll_1.setGeometry(QtCore.QRect(0, 0, 608, 231))
        self.scroll_1.setObjectName("scroll_1")
        self.scroll_history = QtWidgets.QVBoxLayout(self.scroll_1)
        self.scroll_history.setObjectName("scroll_history")
        self.scrollArea_2.setWidget(self.scroll_1)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 10)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem16)
        self.le_query_chef = QtWidgets.QLineEdit(self.groupBox_3)
        self.le_query_chef.setMaxLength(30)
        self.le_query_chef.setObjectName("le_query_chef")
        self.horizontalLayout_13.addWidget(self.le_query_chef)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem17)
        self.bt_query_get_chef = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_query_get_chef.setObjectName("bt_query_get_chef")
        self.horizontalLayout_13.addWidget(self.bt_query_get_chef)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem18)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 2)
        self.horizontalLayout_13.setStretch(2, 1)
        self.horizontalLayout_13.setStretch(3, 6)
        self.horizontalLayout_13.setStretch(4, 1)
        self.horizontalLayout_13.setStretch(5, 2)
        self.horizontalLayout_13.setStretch(6, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem19)
        self.tb_chef_list = QtWidgets.QTextBrowser(self.groupBox_3)
        self.tb_chef_list.setObjectName("tb_chef_list")
        self.verticalLayout_10.addWidget(self.tb_chef_list)
        self.verticalLayout_10.setStretch(0, 3)
        self.verticalLayout_10.setStretch(1, 2)
        self.verticalLayout_10.setStretch(2, 3)
        self.verticalLayout_10.setStretch(3, 15)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem20)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem21)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.le_name = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_name.setMaxLength(30)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout_7.addWidget(self.le_name)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem23)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 5)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 5)
        self.horizontalLayout_7.setStretch(4, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem24)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem25)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem26)
        self.le_phone = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_phone.setMaxLength(10)
        self.le_phone.setObjectName("le_phone")
        self.horizontalLayout_8.addWidget(self.le_phone)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem27)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 5)
        self.horizontalLayout_8.setStretch(2, 1)
        self.horizontalLayout_8.setStretch(3, 5)
        self.horizontalLayout_8.setStretch(4, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem28)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem29)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem30)
        self.le_userid = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_userid.setMaxLength(30)
        self.le_userid.setObjectName("le_userid")
        self.horizontalLayout_9.addWidget(self.le_userid)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem31)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 5)
        self.horizontalLayout_9.setStretch(2, 1)
        self.horizontalLayout_9.setStretch(3, 5)
        self.horizontalLayout_9.setStretch(4, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem32)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem33)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem34)
        self.le_password = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_password.setMaxLength(30)
        self.le_password.setObjectName("le_password")
        self.horizontalLayout_10.addWidget(self.le_password)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem35)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 5)
        self.horizontalLayout_10.setStretch(2, 1)
        self.horizontalLayout_10.setStretch(3, 5)
        self.horizontalLayout_10.setStretch(4, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem36)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem37)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem38)
        self.le_re_password = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_re_password.setMaxLength(30)
        self.le_re_password.setObjectName("le_re_password")
        self.horizontalLayout_11.addWidget(self.le_re_password)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem39)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 5)
        self.horizontalLayout_11.setStretch(2, 1)
        self.horizontalLayout_11.setStretch(3, 5)
        self.horizontalLayout_11.setStretch(4, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem40)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem41)
        self.bt_add_chef = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_add_chef.setObjectName("bt_add_chef")
        self.horizontalLayout_12.addWidget(self.bt_add_chef)
        self.horizontalLayout_12.setStretch(0, 10)
        self.horizontalLayout_12.setStretch(1, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem42)
        self.verticalLayout_9.setStretch(0, 8)
        self.verticalLayout_9.setStretch(1, 2)
        self.verticalLayout_9.setStretch(2, 1)
        self.verticalLayout_9.setStretch(3, 2)
        self.verticalLayout_9.setStretch(4, 1)
        self.verticalLayout_9.setStretch(5, 2)
        self.verticalLayout_9.setStretch(6, 1)
        self.verticalLayout_9.setStretch(7, 2)
        self.verticalLayout_9.setStretch(8, 1)
        self.verticalLayout_9.setStretch(9, 2)
        self.verticalLayout_9.setStretch(10, 1)
        self.verticalLayout_9.setStretch(11, 2)
        self.verticalLayout_9.setStretch(12, 8)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem43 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem43)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem44)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem45)
        self.le_rm_chef = QtWidgets.QLineEdit(self.groupBox)
        self.le_rm_chef.setMaxLength(30)
        self.le_rm_chef.setObjectName("le_rm_chef")
        self.horizontalLayout_6.addWidget(self.le_rm_chef)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem46)
        self.bt_get_rm_chef = QtWidgets.QPushButton(self.groupBox)
        self.bt_get_rm_chef.setObjectName("bt_get_rm_chef")
        self.horizontalLayout_6.addWidget(self.bt_get_rm_chef)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem47)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 6)
        self.horizontalLayout_6.setStretch(4, 1)
        self.horizontalLayout_6.setStretch(5, 2)
        self.horizontalLayout_6.setStretch(6, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        spacerItem48 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem48)
        self.cb_rm_chef = QtWidgets.QComboBox(self.groupBox)
        self.cb_rm_chef.setObjectName("cb_rm_chef")
        self.verticalLayout_8.addWidget(self.cb_rm_chef)
        spacerItem49 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem49)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem50)
        self.bt_rm_confirm = QtWidgets.QPushButton(self.groupBox)
        self.bt_rm_confirm.setObjectName("bt_rm_confirm")
        self.horizontalLayout_5.addWidget(self.bt_rm_confirm)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        spacerItem51 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem51)
        self.verticalLayout_8.setStretch(0, 5)
        self.verticalLayout_8.setStretch(1, 2)
        self.verticalLayout_8.setStretch(2, 1)
        self.verticalLayout_8.setStretch(3, 2)
        self.verticalLayout_8.setStretch(4, 1)
        self.verticalLayout_8.setStretch(5, 2)
        self.verticalLayout_8.setStretch(6, 5)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_6.addWidget(self.textBrowser)
        spacerItem52 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem52)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem53)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_20.addWidget(self.label_14)
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem54)
        self.le_f_name = QtWidgets.QLineEdit(self.groupBox_4)
        self.le_f_name.setObjectName("le_f_name")
        self.horizontalLayout_20.addWidget(self.le_f_name)
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem55)
        self.horizontalLayout_20.setStretch(0, 5)
        self.horizontalLayout_20.setStretch(1, 6)
        self.horizontalLayout_20.setStretch(2, 2)
        self.horizontalLayout_20.setStretch(3, 8)
        self.horizontalLayout_20.setStretch(4, 5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem56)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem57)
        self.le_f_region = QtWidgets.QLineEdit(self.groupBox_4)
        self.le_f_region.setObjectName("le_f_region")
        self.horizontalLayout_17.addWidget(self.le_f_region)
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem58)
        self.horizontalLayout_17.setStretch(0, 5)
        self.horizontalLayout_17.setStretch(1, 6)
        self.horizontalLayout_17.setStretch(2, 2)
        self.horizontalLayout_17.setStretch(3, 8)
        self.horizontalLayout_17.setStretch(4, 5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem59)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem60)
        self.le_f_type = QtWidgets.QLineEdit(self.groupBox_4)
        self.le_f_type.setObjectName("le_f_type")
        self.horizontalLayout_15.addWidget(self.le_f_type)
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem61)
        self.horizontalLayout_15.setStretch(0, 5)
        self.horizontalLayout_15.setStretch(1, 6)
        self.horizontalLayout_15.setStretch(2, 2)
        self.horizontalLayout_15.setStretch(3, 8)
        self.horizontalLayout_15.setStretch(4, 5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem62 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem62)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_18.addWidget(self.label_13)
        spacerItem63 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem63)
        self.le_f_veg = QtWidgets.QLineEdit(self.groupBox_4)
        self.le_f_veg.setObjectName("le_f_veg")
        self.horizontalLayout_18.addWidget(self.le_f_veg)
        spacerItem64 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem64)
        self.horizontalLayout_18.setStretch(0, 5)
        self.horizontalLayout_18.setStretch(1, 6)
        self.horizontalLayout_18.setStretch(2, 2)
        self.horizontalLayout_18.setStretch(3, 8)
        self.horizontalLayout_18.setStretch(4, 5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem65 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem65)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        spacerItem66 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem66)
        self.le_price = QtWidgets.QLineEdit(self.groupBox_4)
        self.le_price.setObjectName("le_price")
        self.horizontalLayout_16.addWidget(self.le_price)
        spacerItem67 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem67)
        self.horizontalLayout_16.setStretch(0, 5)
        self.horizontalLayout_16.setStretch(1, 6)
        self.horizontalLayout_16.setStretch(2, 2)
        self.horizontalLayout_16.setStretch(3, 8)
        self.horizontalLayout_16.setStretch(4, 5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem68 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem68)
        self.bt_add_food = QtWidgets.QPushButton(self.groupBox_4)
        self.bt_add_food.setObjectName("bt_add_food")
        self.horizontalLayout_19.addWidget(self.bt_add_food)
        spacerItem69 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem69)
        self.horizontalLayout_19.setStretch(0, 10)
        self.horizontalLayout_19.setStretch(1, 3)
        self.horizontalLayout_19.setStretch(2, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        spacerItem70 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem70)
        self.verticalLayout_6.setStretch(0, 15)
        self.verticalLayout_6.setStretch(1, 2)
        self.verticalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.setStretch(3, 1)
        self.verticalLayout_6.setStretch(4, 1)
        self.verticalLayout_6.setStretch(5, 1)
        self.verticalLayout_6.setStretch(6, 1)
        self.verticalLayout_6.setStretch(7, 1)
        self.verticalLayout_6.setStretch(8, 5)
        self.horizontalLayout_14.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem71 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem71)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem72 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem72)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_21.addWidget(self.label_16)
        spacerItem73 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem73)
        self.le_name_query = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_name_query.setObjectName("le_name_query")
        self.horizontalLayout_21.addWidget(self.le_name_query)
        spacerItem74 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem74)
        self.bt_get = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_get.setObjectName("bt_get")
        self.horizontalLayout_21.addWidget(self.bt_get)
        spacerItem75 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem75)
        self.horizontalLayout_21.setStretch(0, 2)
        self.horizontalLayout_21.setStretch(1, 3)
        self.horizontalLayout_21.setStretch(2, 2)
        self.horizontalLayout_21.setStretch(3, 8)
        self.horizontalLayout_21.setStretch(4, 2)
        self.horizontalLayout_21.setStretch(5, 3)
        self.horizontalLayout_21.setStretch(6, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        spacerItem76 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem76)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem77 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem77)
        self.cb_rm_food = QtWidgets.QComboBox(self.groupBox_5)
        self.cb_rm_food.setObjectName("cb_rm_food")
        self.horizontalLayout_23.addWidget(self.cb_rm_food)
        spacerItem78 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem78)
        self.horizontalLayout_23.setStretch(0, 5)
        self.horizontalLayout_23.setStretch(1, 30)
        self.horizontalLayout_23.setStretch(2, 5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        spacerItem79 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem79)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem80 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem80)
        self.bt_rm_food = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_rm_food.setObjectName("bt_rm_food")
        self.horizontalLayout_22.addWidget(self.bt_rm_food)
        spacerItem81 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem81)
        self.bt_add_img = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_add_img.setObjectName("bt_add_img")
        self.horizontalLayout_22.addWidget(self.bt_add_img)
        spacerItem82 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem82)
        self.bt_rm_img = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_rm_img.setObjectName("bt_rm_img")
        self.horizontalLayout_22.addWidget(self.bt_rm_img)
        spacerItem83 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem83)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 3)
        self.horizontalLayout_22.setStretch(2, 1)
        self.horizontalLayout_22.setStretch(3, 3)
        self.horizontalLayout_22.setStretch(4, 1)
        self.horizontalLayout_22.setStretch(5, 3)
        self.horizontalLayout_22.setStretch(6, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        spacerItem84 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem84)
        self.verticalLayout_7.setStretch(0, 5)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(4, 1)
        self.verticalLayout_7.setStretch(5, 1)
        self.verticalLayout_7.setStretch(6, 5)
        self.horizontalLayout_14.addWidget(self.groupBox_5)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem85 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem85)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem86 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem86)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem87 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem87)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem88 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem88)
        self.lb_no = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_no.setFont(font)
        self.lb_no.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_no.setObjectName("lb_no")
        self.horizontalLayout_28.addWidget(self.lb_no)
        spacerItem89 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem89)
        self.lb_table_no_2 = QtWidgets.QLabel(self.tab_5)
        self.lb_table_no_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_table_no_2.setObjectName("lb_table_no_2")
        self.horizontalLayout_28.addWidget(self.lb_table_no_2)
        spacerItem90 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem90)
        self.horizontalLayout_28.setStretch(0, 2)
        self.horizontalLayout_28.setStretch(1, 5)
        self.horizontalLayout_28.setStretch(2, 2)
        self.horizontalLayout_28.setStretch(3, 1)
        self.horizontalLayout_28.setStretch(4, 2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        spacerItem91 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem91)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem92 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem92)
        self.le_table_no = QtWidgets.QLineEdit(self.tab_5)
        self.le_table_no.setAlignment(QtCore.Qt.AlignCenter)
        self.le_table_no.setObjectName("le_table_no")
        self.horizontalLayout_26.addWidget(self.le_table_no)
        spacerItem93 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem93)
        self.bt_change = QtWidgets.QPushButton(self.tab_5)
        self.bt_change.setObjectName("bt_change")
        self.horizontalLayout_26.addWidget(self.bt_change)
        spacerItem94 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem94)
        self.horizontalLayout_26.setStretch(0, 4)
        self.horizontalLayout_26.setStretch(1, 1)
        self.horizontalLayout_26.setStretch(2, 3)
        self.horizontalLayout_26.setStretch(3, 4)
        self.horizontalLayout_26.setStretch(4, 4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        spacerItem95 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem95)
        self.horizontalLayout_27.addLayout(self.verticalLayout_11)
        spacerItem96 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem96)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 1)
        self.horizontalLayout_27.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        spacerItem97 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem97)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_refresh_on_order.setText(_translate("Form", "Refresh"))
        self.lb_name.setText(_translate("Form", "Name"))
        self.lb_table_no.setText(_translate("Form", "Table No."))
        self.lb_status.setText(_translate("Form", "Status"))
        self.lb_total.setText(_translate("Form", "Total"))
        self.label_17.setText(_translate("Form", "Bill Print"))
        self.label_18.setText(_translate("Form", "Payment Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "On Order"))
        self.label.setText(_translate("Form", "Start : "))
        self.label_3.setText(_translate("Form", "To"))
        self.label_2.setText(_translate("Form", "End : "))
        self.bt_t_sale.setText(_translate("Form", "Total Sale"))
        self.bt_get_orders.setText(_translate("Form", "Get Orders"))
        self.label_20.setText(_translate("Form", "Person Name"))
        self.label_22.setText(_translate("Form", "Order No."))
        self.label_21.setText(_translate("Form", "In Time"))
        self.label_19.setText(_translate("Form", "Payment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "History"))
        self.groupBox_3.setTitle(_translate("Form", "Query Chef"))
        self.label_10.setText(_translate("Form", "Name : "))
        self.bt_query_get_chef.setText(_translate("Form", "Get"))
        self.groupBox_2.setTitle(_translate("Form", "Add Chef"))
        self.label_5.setText(_translate("Form", "Name : "))
        self.label_6.setText(_translate("Form", "Phone No. : "))
        self.label_7.setText(_translate("Form", "User ID : "))
        self.label_8.setText(_translate("Form", "Password : "))
        self.label_9.setText(_translate("Form", "Re-Enter Password : "))
        self.bt_add_chef.setText(_translate("Form", "Add"))
        self.groupBox.setTitle(_translate("Form", "Remove Chef"))
        self.label_4.setText(_translate("Form", "Name : "))
        self.bt_get_rm_chef.setText(_translate("Form", "Get"))
        self.bt_rm_confirm.setText(_translate("Form", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Manage Chef"))
        self.groupBox_4.setTitle(_translate("Form", "Add Food"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:6.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#2b2b2b;\"><span style=\" font-family:\'Consolas\'; font-size:10.5pt; color:#a9b7c6; background-color:#2b2b2b;\">Region : [North Indian - nid, South Indian - sid, Italian - ita, Thai - thi, Chinese - chi, Rajasthani - raj, Continental - conti, None - none]</span><span style=\" font-family:\'Consolas\'; font-size:10.5pt; color:#a9b7c6;\"><br /></span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#2b2b2b;\"><span style=\" font-family:\'Consolas\'; font-size:10.5pt; color:#a9b7c6;\">Type : [Starter - sta, Dessert - des, Main Course - mcs, Refreshments - ref, Bread - bre]</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#2b2b2b;\"><span style=\" font-family:\'Consolas\'; font-size:10.5pt; color:#a9b7c6;\">Veg : [If Veg - True, Else - False]</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "Name"))
        self.label_11.setText(_translate("Form", "Region"))
        self.label_12.setText(_translate("Form", "Type"))
        self.label_13.setText(_translate("Form", "Veg"))
        self.label_15.setText(_translate("Form", "Price"))
        self.bt_add_food.setText(_translate("Form", "Add"))
        self.groupBox_5.setTitle(_translate("Form", "Change"))
        self.label_16.setText(_translate("Form", "Name "))
        self.bt_get.setText(_translate("Form", "Get"))
        self.bt_rm_food.setText(_translate("Form", "Remove Food"))
        self.bt_add_img.setText(_translate("Form", "Add Image"))
        self.bt_rm_img.setText(_translate("Form", "Remove Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Manage Food"))
        self.lb_no.setText(_translate("Form", "Current No. Of Tables : "))
        self.lb_table_no_2.setText(_translate("Form", "n"))
        self.bt_change.setText(_translate("Form", "Change"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Restaurant"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

