from backend.manager.threads.add_food.th_m_get_food_list import ThreadFetchFoodList
from backend.manager.threads.history.th_fetch_bill_history import ThreadBillHistoryFetch
from backend.manager.threads.login_code.th_manager_login import ThreadManagerLogin
from backend.manager.threads.manage_chef.th_query_chef import ThreadQueryChef
from backend.manager.threads.on_order.th_payment_done import ThreadPaymentDone
from backend.manager.threads.restau.th_change_table_no import ThreadChangeTableNo
